# Generated by Django 2.2 on 2020-05-18 06:17

from django.db import migrations
import tinymce.models


class Migration(migrations.Migration):

    dependencies = [
        ('GWHK', '0004_companynews'),
    ]

    operations = [
        migrations.AlterField(
            model_name='pressrelease',
            name='content',
            field=tinymce.models.HTMLField(),
        ),
    ]
