# Generated by Django 2.2 on 2020-05-18 06:36

import ckeditor.fields
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('GWHK', '0005_auto_20200518_1417'),
    ]

    operations = [
        migrations.AlterField(
            model_name='companynews',
            name='content',
            field=ckeditor.fields.RichTextField(),
        ),
    ]
