# Generated by Django 2.2 on 2020-05-18 06:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('GWHK', '0006_auto_20200518_1436'),
    ]

    operations = [
        migrations.AlterField(
            model_name='jobopenings',
            name='jobRequirements',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='jobopenings',
            name='jobRespons',
            field=models.TextField(blank=True, null=True),
        ),
    ]
