# Generated by Django 2.2 on 2020-05-18 07:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('GWHK', '0007_auto_20200518_1453'),
    ]

    operations = [
        migrations.AlterField(
            model_name='companynews',
            name='content',
            field=models.TextField(),
        ),
        migrations.AlterField(
            model_name='pressrelease',
            name='content',
            field=models.TextField(),
        ),
    ]
